### ISSUE TITLE
Profile upload reports "Profile could not be parsed    unknow protocol: urn" when attempting to upload custom profiles

### ISSUE THREAD

**Issue by matthew-morris-cessda** [cessda/cessda.cmv.server#215]
From @katja-moilanen 

> I noticed that the graphical user interface of the CMV does not work when trying to use "Upload files" for profile.
> 
> I was trying to test if my changes to profiles work but I got only error message "Profile could not be parsed    unknow protocol: urn". Then I tried to upload old versions of profiles, but I got the same error message every time. Therefore, I assume that the problem is in CMV.

**Comment by matthew-morris-cessda** [comment]
This was fixed (by accident) in #214

@katja-moilanen - could you test this at https://cmv-staging.cessda.eu/

**Comment by katja-moilanen** [comment]
@matthew-morris-cessda
https://cmv-staging.cessda.eu/ works. I was able to validate using uploaded profiles.
