### ISSUE TITLE
Return a message "No Constraint Violations found" instead of empty box when there are no constraint violations

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv.server#29]
**Original report on BitBucket by Alexander Mühlbauer.**

----------------------------------------

* Feedback by Olof Olssen on 2020/10/28 by mail

‌

**Comment by matthew-morris-cessda** [comment]
Resolved in #82.

![image](https://user-images.githubusercontent.com/68543725/224056407-3555fa73-30f5-47f6-b310-89d9df0e6f07.png)
