### ISSUE TITLE
Add Matomo Cloud tracking code

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv.server#56]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

The code snippet must list the Cloud instance as the first tracker.

On the main [cessda.eu](http://cessda.eu/) website, dual tracking is already implemented, with the full code snippet being as follows \(ids have been updated for this application\)

  
<script type="text/javascript">  
var \_paq = window.\_paq = window.\_paq || \[\];  
/\* tracker methods like "setCustomDimension" should be called before "trackPageView" \*/  
\_paq.push\(\["setDoNotTrack", true\]\);  
\_paq.push\(\['trackPageView'\]\);  
\_paq.push\(\['enableLinkTracking'\]\);  
\(function\(\) \{  
var u="[https://cessda.matomo.cloud/](https://www.google.com/url?q=https://cessda.matomo.cloud/&sa=D&source=editors&ust=1621329582532000&usg=AOvVaw0LX_ICfVT-mCDcxQHa458r)";  
\_paq.push\(\['setTrackerUrl', u\+'matomo.php'\]\);  
\_paq.push\(\['setSiteId', '8'\]\);  
var secondaryTrackerUrl = '[https://analytics.cessda.eu/matomo.php](https://www.google.com/url?q=https://analytics.cessda.eu/matomo.php&sa=D&source=editors&ust=1621329582532000&usg=AOvVaw3aMnGD7LbeLguZSplNMvE3)';  
var secondaryWebsiteId = 8;  
\_paq.push\(\['addTracker', secondaryTrackerUrl, secondaryWebsiteId\]\);  
var d=document, g=d.createElement\('script'\), s=d.getElementsByTagName\('script'\)\[0\];  
g.type='text/javascript'; g.async=true; g.src='[//cdn.matomo.cloud/cessda.matomo.cloud/matomo.js](//cdn.matomo.cloud/cessda.matomo.cloud/matomo.js)'; s.parentNode.insertBefore\(g,s\);  
\}\)\(\);  
</script>

**Comment by matthew-morris-cessda** [comment]
See https://github.com/cessda/cessda.cmv.server/blob/main/src/main/webapp/VAADIN/themes/cmv/layouts/header.html#L2

**Comment by john-shepherdson** [comment]
Doesn't seem to be working. Snippet regenerated on 3/4/2023


<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://cessda.matomo.cloud/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '8']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src='//cdn.matomo.cloud/cessda.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
