### ISSUE TITLE
Test M4 functionality, prior to release to production

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv.server#58]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Check that basic functionally is still available to users.

**Comment by matthew-morris-cessda** [comment]
UI interaction:

![image](https://user-images.githubusercontent.com/68543725/213443297-dbd5686b-80b6-4726-ad91-697c37b2caee.png)

**Comment by matthew-morris-cessda** [comment]
REST API response:

![image](https://user-images.githubusercontent.com/68543725/213443688-fd3d74fe-4218-4000-98ed-29bee08af108.png)

**Comment by matthew-morris-cessda** [comment]
User functionality tested
